pipeline{
    agent{
        docker {
            image  'python:3.11-slim'
            args    '-u root'
        }
    }
    stages{
        stage("checkout-code"){
            steps{
                checkout scm
            
            }
        }
        stage("install dependencies"){
            steps{
                sh ''' 
                cat /etc/os-release
                ls -lart
                cd python-api-yt
                ls -lart
                pip install -r requirements.txt
            
                '''
            }
        }
        stage("run the test"){
            steps{
                sh '''
                cd python-api-yt
                ls -lart
                python -m pytest -v -s
                '''
            }
        }
        stage("archive results"){
            steps{
                sh "result"
            }
        }
    }
    post{
        success{
            echo "Build and test passed"
        }
        failure{
            echo "Build test failed"
        }
    }

}
