@Library('sdet-python-library')


pipeline {
    agent any
      parameters {
        booleanParam(name: 'CREATE_TAG', defaultValue: false, description: 'Check to create a release tag')
    }
    stages {
        stage('environment'){
            steps{
               setupEnv()
            }
        }
        stage("check out scm"){
            steps{
                checkout scm
            }

        }
        stage("Branch/PR Info") {
            steps {
                script {
                    echo "BRANCH_NAME: ${env.BRANCH_NAME}"
                    echo "CHANGE_ID: ${env.CHANGE_ID}"
                    echo "CHANGE_TARGET: ${env.CHANGE_TARGET}"
                }
            }
        }

        // PR VALIDATION
        stage("PR Validation Checks") {
            when {
                changeRequest()
                
            }
            agent{
                docker {
                    image  'python:3.11-slim'
                    // args    "--user=${env.USER_ID}:${env.GROUP_ID}"
                    args   "-u root"
                }
            }
           stages{
               stage("PR Name check"){
                    steps{
                prCheck()
                }
            }

               }
            stage("quality code and checks"){
                parallel{
               stage("Lint"){
                   steps{
                       lintcode()
                   }
               }
               stage("sonar checks"){
                   steps{
                       sonarCheck()
                   }
               }
         
          

            stage("build and test"){
            steps{
                buildandtest()
                
        }}}
            }}
    
        
        stage("MAIN BRANCH CI/CD"){
            when{
                branch 'cdn-1123'

            }
            stages{
                stage("lint"){
                    steps{
                        
                           lintcode()
                         
                         }
                         }
                stage("build"){
                    steps{
                        
                         echo "build can do later"
                    }
                }
                stage("tag build"){
                    when {
                        allOf{
                            branch 'cdn-1123'
                            expression {params.CREATE_TAG==true}
                        }
                    }
                    steps{
                        createTag()
                    }
                }
                    }
                }
            }
        
        // FULL PIPELINE
       
    

    post {
        success {
            echo "Pipeline completed successfully"
        }
        failure {
            echo "Pipeline failed"
        }
        always{
            echo 'Cleaning working dir'
            echo "USER_ID=${env.USER_ID}"
            echo "GROUP_ID=${env.GROUP_ID}"
            sh """
            chown -R  ${USER_ID}:${GROUP_ID} *
            """
            // The `deleteDir()` command handles all cleanup. No need for `chown`
            deleteDir()
            echo "cleaned dir"
        }
    }

}
