pipeline {
    agent { label 'agent-1' } // Specify the agent using a label
    // options {
    //     ansiColor('xterm') // Enable ANSI color in logs
    // }


    // parameters {
    //     string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')

    //     text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')

    //     booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')

    //     choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')

    //     password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
    // }
   
    stages {
        stage('install dependecies') {
          
            steps {
                sh 'ls -lart'
                sh 'cd catalogue'
                sh 'npm install' // Fixed missing space and quotes
            }
        }
        stage('scan the code'){
            steps{
                sh 'pwd'
                sh 'ls -lart'
                sh 'cd catalogue'
                sh 'sonar-scanner'
            }
        }
        
    }
    post {
        success {
            echo "it will work for success"
        }
        failure {
            echo "it will work for failure"
        }
    }
}
